apiVersion: v1
kind: Secret
metadata:
  name: weaviate-cluster-api-basic-auth
type: kubernetes.io/basic-auth
data:
  username: {{ if .Values.clusterApi.username }}{{ .Values.clusterApi.username | b64enc | quote }}{{ else }}{{ include "cluster_api.secret" . | indent 2 | b64enc }}{{ end }}
  password: {{ if .Values.clusterApi.password }}{{ .Values.clusterApi.password | b64enc | quote }}{{ else }}{{ include "cluster_api.secret" . | indent 2 | b64enc }}{{ end }}